baseURL = 'https://github.com/alfred-saker/ScareBlog'
languagecode = "fr"
title = 'ScareBlog'
theme = "hugo-coder"
defaultcontentlanguage = "en"
paginate = 20

disqusShortname = "yourdiscussshortname"

[markup.highlight]
style = "github-dark"

[params]
  author = "Alfred KUATE"
  info = "Developpeur Full-Stack"
  description = "John Doe's personal website"
  keywords = "blog,developer,personal"
  avatarurl = "images/user.jpg"
  #gravatar = "john.doe@example.com"

  faviconSVG = "/img/favicon.svg"
  favicon_32 = "/img/favicon-32x32.png"
  favicon_16 = "/img/favicon-16x16.png"

  since = 2019

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

  # customCSS = ["css/custom.css"]
  # customSCSS = ["scss/custom.scss"]
  # customJS = ["js/custom.js"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 1
  url = "https://github.com/alfred-saker/"
[[params.social]]
  name = "Linkedin"
  icon = "fa fa-linkedin fa-2x"
  weight = 2
  url = "https://www.linkedin.com/in/alfred-kuate"
[[params.social]]
  name = "Portfolio"
  icon = "fa fa-globe fa-2x"
  weight = 3
  url = "https://portfoliodev2023.netlify.app/"

# Menu links
[[menu.main]]
  name = "Blog"
  weight = 1
  url  = "posts/"
[[menu.main]]
  name = "A propos"
  weight = 2
  url = "about/"
[[menu.main]]
  name = "Contact"
  weight = 2
  url = "contact/"